# Generated by Django 3.0.1 on 2020-03-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='informacao',
            options={'verbose_name': 'Informação', 'verbose_name_plural': 'Informações'},
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='linha',
            options={'verbose_name': 'Linha', 'verbose_name_plural': 'Linhass'},
        ),
        migrations.AlterModelOptions(
            name='pesquisador',
            options={'verbose_name': 'Pesquisador', 'verbose_name_plural': 'Pesquisadores'},
        ),
        migrations.AlterModelOptions(
            name='premiacao',
            options={'verbose_name': 'Premiação', 'verbose_name_plural': 'Premiações'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'Sobre', 'verbose_name_plural': 'Sobre'},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
    ]
