# Generated by Django 3.0.1 on 2020-03-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200304_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobre',
            name='sigla',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
