# Generated by Django 3.0.1 on 2020-03-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sobre_sigla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacao',
            old_name='instituicao',
            new_name='instituicoes',
        ),
    ]
