# Generated by Django 3.0.1 on 2020-03-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200304_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='sigla',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Livro', 'Livro'), ('Journal Papers', 'Journal Papers'), ('Conference Papers', 'Conference Papers'), ('Keynote Speeches', 'Keynote Speeches'), ('Outro', 'Outro')], max_length=256, null=True),
        ),
    ]
