# Generated by Django 2.2.12 on 2020-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sobre_mapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Parceiros/Colaboradores', 'verbose_name_plural': 'Parceiros/Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='linha',
            options={'verbose_name': 'Linha de Pesquisa', 'verbose_name_plural': 'Linhas de Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Produção', 'verbose_name_plural': 'Produções'},
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Artigos completos publicados em periódicos', 'Artigos completos publicados em periódicos'), ('Artigos aceitos para publicação', 'Artigos aceitos para publicação'), ('Livros e capítulos', 'Livros e capítulos'), ('Texto em jornal ou revista (magazine)', 'Texto em jornal ou revista (magazine)'), ('Trabalhos publicados em anais de eventos', 'Trabalhos publicados em anais de eventos'), ('Apresentação de trabalho e palestra', 'Apresentação de trabalho e palestra'), ('Partitura musical', 'Partitura musical'), ('Tradução', 'Tradução'), ('Prefácio, posfácio', 'Prefácio, posfácio'), ('Outra produção bibliográfica', 'Outra produção bibliográfica'), ('Assessoria e consultoria', 'Assessoria e consultoria'), ('Extensão tecnológica', 'Extensão tecnológica'), ('Programa de computador sem registro', 'Programa de computador sem registro'), ('Produtos', 'Produtos'), ('Processos ou técnicas', 'Processos ou técnicas'), ('Trabalhos técnicos', 'Trabalhos técnicos'), ('Cartas, mapas ou similares', 'Cartas, mapas ou similares'), ('Curso de curta duração ministrado', 'Curso de curta duração ministrado'), ('Desenvolvimento de material didático ou instrucional', 'Desenvolvimento de material didático ou instrucional'), ('Editoração', 'Editoração'), ('Manutenção de obra artística', 'Manutenção de obra artística'), ('Maquete', 'Maquete'), ('Entrevistas, mesas redondas, programas e comentários na mídia', 'Entrevistas, mesas redondas, programas e comentários na mídia'), ('Relatório de pesquisa', 'Relatório de pesquisa'), ('Redes sociais, websites e blogs', 'Redes sociais, websites e blogs'), ('Outra produção técnica', 'Outra produção técnica'), ('Artes cênicas', 'Artes cênicas'), ('Música', 'Música'), ('Artes visuais', 'Artes visuais'), ('Outra produção artística/cultural', 'Outra produção artística/cultural')], max_length=256, null=True),
        ),
    ]
