# Generated by Django 2.2.12 on 2020-05-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pesquisador_descricao_completa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='descricao_completa',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
