# Generated by Django 2.2.12 on 2020-05-18 13:38

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0008_auto_20200516_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projeto',
            new_name='Portifolio',
        ),
        migrations.AlterModelOptions(
            name='portifolio',
            options={'verbose_name': 'Portifolio', 'verbose_name_plural': 'Portifolios'},
        ),
    ]
