# Generated by Django 2.2.12 on 2020-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200516_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='orcid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
