# Generated by Django 2.2.12 on 2020-05-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200518_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=256, null=True)),
                ('descricao', models.TextField(blank=True, max_length=1024, null=True)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to='core.Pesquisador')),
                ('pesquisadores', models.ManyToManyField(to='core.Pesquisador')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.AddField(
            model_name='informacao',
            name='portifolio',
            field=models.ManyToManyField(to='core.Portifolio'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='projetos',
            field=models.ManyToManyField(to='core.Projeto'),
        ),
    ]
