# Generated by Django 2.2.12 on 2020-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200518_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacao',
            name='portifolio',
        ),
        migrations.AlterField(
            model_name='informacao',
            name='projetos',
            field=models.ManyToManyField(to='core.Portifolio'),
        ),
    ]
