# Generated by Django 2.2.12 on 2020-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200518_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='projetos',
            field=models.ManyToManyField(to='core.Projeto'),
        ),
    ]
