# Generated by Django 2.2.12 on 2020-05-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_informacao_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='integrantes',
            field=models.ManyToManyField(to='core.Pesquisador'),
        ),
    ]
