# Generated by Django 2.2.12 on 2020-05-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_projeto_integrantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
