# Generated by Django 2.2.12 on 2020-05-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pesquisador_orcid'),
        ('core', '0015_auto_20200518_1104'),
    ]

    operations = [
    ]
