# Generated by Django 2.2.12 on 2020-05-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200518_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacao',
            old_name='descricao',
            new_name='descricao_infraestrutura',
        ),
    ]
