# Generated by Django 2.2.12 on 2020-05-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200518_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacao',
            old_name='imagem_infraestrutura',
            new_name='imagem_infraestrutura1',
        ),
        migrations.AddField(
            model_name='informacao',
            name='imagem_infraestrutura2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='informacao',
            name='imagem_infraestrutura3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
