# Generated by Django 2.2.12 on 2020-05-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200519_1617'),
        ('core', '0019_auto_20200518_1746'),
        ('core', '0008_auto_20200517_1237'),
        ('core', '0016_merge_20200519_1549'),
    ]

    operations = [
    ]
