# Generated by Django 2.2.12 on 2020-05-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20200519_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Inscrito',
                'verbose_name_plural': 'Inscritos',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='inscritos',
            field=models.ManyToManyField(to='core.Inscrito'),
        ),
    ]
