# Generated by Django 2.2.12 on 2020-05-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='documentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Documento'),
        ),
    ]
