# Generated by Django 2.2.12 on 2020-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_informacao_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacao',
            name='documentos',
        ),
        migrations.AddField(
            model_name='informacao',
            name='documentos',
            field=models.ManyToManyField(to='core.Documento'),
        ),
    ]
