# Generated by Django 2.2.12 on 2020-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_grupo_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome')),
                ('email', models.CharField(max_length=256, verbose_name='E-mail')),
                ('assunto', models.CharField(max_length=256, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Formulário',
                'verbose_name_plural': 'Formulários',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='formularios',
            field=models.ManyToManyField(to='core.Formulario'),
        ),
    ]
