# Generated by Django 2.2.12 on 2020-05-24 03:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200523_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='formularios',
            field=models.ManyToManyField(blank=True, to='core.Formulario'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='imagem_infraestrutura1',
            field=models.ImageField(blank=True, upload_to=core.models.caminho),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='imagem_infraestrutura2',
            field=models.ImageField(blank=True, upload_to=core.models.caminho),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='imagem_infraestrutura3',
            field=models.ImageField(blank=True, upload_to=core.models.caminho),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='informacoes',
            field=models.ManyToManyField(blank=True, to='core.Informacao'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='inscritos',
            field=models.ManyToManyField(blank=True, to='core.Inscrito'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='newsletters',
            field=models.ManyToManyField(blank=True, to='core.Newsletter'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='instituicoes',
            field=models.ManyToManyField(blank=True, to='core.Instituicao'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='linhas',
            field=models.ManyToManyField(blank=True, to='core.Linha'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='pesquisadores',
            field=models.ManyToManyField(blank=True, to='core.Pesquisador'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='portifolio',
            field=models.ManyToManyField(blank=True, to='core.Portifolio'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='premiacoes',
            field=models.ManyToManyField(blank=True, to='core.Premiacao'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='core.Projeto'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='publicacoes',
            field=models.ManyToManyField(blank=True, to='core.Publicacao'),
        ),
        migrations.AlterField(
            model_name='informacao',
            name='servicos',
            field=models.ManyToManyField(blank=True, to='core.Servico'),
        ),
    ]
