# Generated by Django 2.2.12 on 2020-05-24 03:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200524_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=core.models.caminho),
        ),
    ]
