# Generated by Django 2.2.12 on 2020-05-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200525_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacao',
            old_name='portifolio',
            new_name='portifolios',
        ),
    ]
