# Generated by Django 2.2.12 on 2020-05-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200526_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacao',
            old_name='portifolios',
            new_name='portifolio',
        ),
    ]
