# Generated by Django 2.2.12 on 2020-05-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200523_2021'),
        ('core', '0031_auto_20200526_0154'),
    ]

    operations = [
    ]
