# Generated by Django 2.2.12 on 2020-05-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20200527_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.RemoveField(
            model_name='informacao',
            name='documentos',
        ),
        migrations.AddField(
            model_name='grupo',
            name='documentos',
            field=models.ManyToManyField(blank=True, to='core.Documento'),
        ),
    ]
