# Generated by Django 2.2.12 on 2020-05-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200527_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='publicar',
            field=models.BooleanField(default=False, verbose_name='Publicar como notícia'),
            preserve_default=False,
        ),
    ]
