# Generated by Django 2.2.12 on 2020-05-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_newsletter_publicar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='publicar',
            new_name='publicado',
        ),
    ]
