# Generated by Django 2.2.12 on 2020-05-28 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200528_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
