# Generated by Django 2.2.12 on 2020-05-28 19:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200528_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to=core.models.caminho_arquivo),
        ),
    ]
